#:schema node_modules/wrangler/config-schema.json
name = "cyclical-worker"
main = "index.ts"
compatibility_date = "2024-12-18"

# Workers Logs
[observability]
enabled = true

# [placement]
# mode = "smart"

[[services]]
service = "cyclical-worker"
binding = "CyclicalWorker"
